name: praylib-wasm-build
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - conda-forge
dependencies:
  - cmake
  - pkg-config
  - emscripten_emscripten-wasm32==3.1.73
  - empack
  - python
  - pip
  - setuptools
  - micromamba
  - rattler-build
  - curl